theme: minima

# Configuración adicional
title: "Manual de Usuario - NALVE"
description: "Documentación oficial de NALVE"
baseurl: "/docs" # Si tu sitio está en una subcarpeta
url: "https://neestoralvz.github.io/manual_nalve/" # Cambia esto por tu URL de GitHub Pages
