# Configuraci칩n b치sica del sitio
title: "Manual de Usuario - NALVE"
description: "Documentaci칩n oficial de NALVE"
baseurl: "/manual_nalve"
url: "https://neestoralvz.github.io"

# Tema
remote_theme: jekyll/minima
theme: minima
minima:
  skin: dark

# Plugins esenciales
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Configuraci칩n de Markdown
markdown: kramdown
kramdown:
  input: GFM
